import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`.myImg {
          border-radius: 18px;
  margin-top: 21px;
        }`}
      </style>
      <Head>
        <title>hunting Coder App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1> <span className='mySpan'>Hunting Coders</span></h1>
        <div className="myImg">
          <img className={styles.myImg} src="/home.png" alt="" width={237} height={158} />
        </div>

        <p className={styles.description}>
          A blog for hunting coders by a coder
        </p>
        <div>
          <h2>Popular Blogs</h2>
          <div className={styles.blogItem}>
          <Link href={`blog-post/how-to-learn-javascript`}> <h3>How to learn javascript in 2022</h3></Link>
           
            <p > Javascript the language used to design logic for web</p>
          </div>

          <div className={styles.blogItem}>
            <h3>How to learn python in 2022</h3>
            <p > Javascript the language used to design logic for web</p>
          </div>

          <div className={styles.blogItem}>
            <h3>How to learn Nextjs in 2022</h3>
            <p > Javascript the language used to design logic for web</p>
          </div>
        </div>
      </main>
    </div>

  )
}
