import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className={styles.container}>

      <style jsx>
        {`.myImg {
          border-radius: 18px;
  margin-top: 21px;
        }`}
      </style>
      <Head>
        <title>hunting Coder App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          <li>
            <Link href="/blog">Blog</Link>
          </li>
          <li>
            <Link href="/contect">Contect</Link>
          </li>
        </ul>

      </nav >
      <main className={styles.main}>
        <h1> <span className='mySpan'>Hunting Coders</span></h1>
        <div className="myImg"><Image className={styles.myImg} src="/home.png" alt="" width={237} height={158} /></div>

        <p className={styles.description}>
          A blog for hunting coders by a coder
        </p>
        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blog">
            <h3>How to learn javascript in 2022</h3>
            <p > Javascript the language used to design logic for web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blog">
            <h3>How to learn javascript in 2022</h3>
            <p > Javascript the language used to design logic for web</p>
          </div>
        </div>
        <div className="blogs">
          <div className="blog">
            <h3>How to learn javascript in 2022</h3>
            <p > Javascript the language used to design logic for web</p>
          </div>
        </div>
      </main>
    </div>

  )
}
